import React, { useState } from 'react';

export const SeoArticle: React.FC = () => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className="w-full mx-auto bg-gray-900/80 p-6 rounded-xl border border-gray-800 relative overflow-hidden">
      <script type="application/ld+json">
        {JSON.stringify({
          "@context": "https://schema.org",
          "@graph": [
            {
              "@type": "Article",
              "headline": "Sitemap Generator Pro: The Ultimate Guide to Technical SEO",
              "image": ["https://doodax.com/favicon.svg"],
              "datePublished": "2023-11-01T08:00:00+08:00",
              "dateModified": new Date().toISOString(),
              "author": [{
                  "@type": "Person",
                  "name": "HSINI MOHAMED",
                  "url": "https://github.com/hsinidev"
              }],
              "publisher": {
                "@type": "Organization",
                "name": "Doodax",
                "logo": {
                  "@type": "ImageObject",
                  "url": "https://doodax.com/favicon.svg"
                }
              }
            },
            {
              "@type": "FAQPage",
              "mainEntity": [
                {
                  "@type": "Question",
                  "name": "Is this sitemap generator free?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes, Sitemap Generator Pro is 100% free and open source. It is maintained as a contribution to the web developer community."
                  }
                },
                {
                  "@type": "Question",
                  "name": "Does Google guarantee indexing after submitting a sitemap?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "No. A sitemap is a suggestion, not a command. However, it significantly improves the chances of your pages being discovered and indexed faster."
                  }
                },
                {
                  "@type": "Question",
                  "name": "How do I submit the XML file to Google?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Download the XML file generated by this tool, upload it to your website's root directory (e.g., public_html), and then submit the URL to Google Search Console."
                  }
                }
              ]
            }
          ]
        })}
      </script>

      <h2 className="text-2xl font-bold text-gold mb-4">About This Project</h2>

      {/* Content Container with dynamic height for 'Read More' functionality */}
      <div className={`relative transition-all duration-500 ease-in-out ${!isExpanded ? 'max-h-[3.5rem] overflow-hidden' : 'max-h-[8000px]'}`}>
        
        <article className="prose prose-invert prose-sm sm:prose-base max-w-none text-gray-300">
          <p className="font-medium text-white mb-4">
             Sitemap Generator Pro (doodax.com) is a cutting-edge, browser-based utility designed to democratize technical SEO. 
             In an era where search visibility defines business success, having a technically sound website architecture is paramount.
          </p>

          {/* Hidden content starts here visually when collapsed */}
          <div className={!isExpanded ? 'opacity-50' : 'opacity-100 transition-opacity duration-700'}>
            
            <div className="bg-gray-800 p-4 rounded-lg my-6 border-l-4 border-gold">
                <h3 className="text-lg font-bold text-white m-0">Table of Contents</h3>
                <nav className="mt-2 grid md:grid-cols-2 gap-2 text-sm">
                    <a href="#chapter1" className="hover:text-gold transition-colors">• The Importance of XML Sitemaps</a>
                    <a href="#chapter2" className="hover:text-gold transition-colors">• How Doodax.com Works</a>
                    <a href="#chapter3" className="hover:text-gold transition-colors">• Advanced Configuration</a>
                    <a href="#chapter4" className="hover:text-gold transition-colors">• SEO Best Practices 2024</a>
                    <a href="#faq" className="hover:text-gold transition-colors">• Frequently Asked Questions</a>
                </nav>
            </div>

            <h3 id="chapter1" className="text-xl font-bold text-gold mt-8">1. The Importance of XML Sitemaps in Modern SEO</h3>
            <p>
                Search engines like Google, Bing, and Yahoo use complex algorithms and "crawlers" (or spiders) to discover content on the web. 
                While these bots are sophisticated, they aren't perfect. They rely heavily on links to traverse from one page to another. 
                If your website has isolated pages, deep architecture, or dynamic content, crawlers might miss significant portions of your site.
            </p>
            <p>
                This is where an <strong>XML Sitemap</strong> becomes crucial. Think of it as a roadmap that you hand directly to the search engine. 
                It lists every URL you want indexed, along with vital metadata:
            </p>
            <ul className="list-disc pl-5 space-y-2">
                <li><strong>Last Modified Date:</strong> Tells Google when content was updated, prompting a re-crawl.</li>
                <li><strong>Priority:</strong> Indicates the relative importance of pages within your site structure.</li>
                <li><strong>Change Frequency:</strong> A hint to crawlers about how often they should check back.</li>
            </ul>

            <h3 id="chapter2" className="text-xl font-bold text-gold mt-8">2. How Doodax.com Revolutionizes the Process</h3>
            <p>
                Traditional sitemap generation often involves server-side plugins, paid subscriptions, or complex command-line tools. 
                <strong>Sitemap Generator Pro</strong> changes this paradigm by offering a client-side solution.
            </p>
            <p>
                <strong>Privacy First:</strong> Unlike other online generators that harvest your data, Doodax.com runs entirely in your browser. 
                Your URLs are processed via JavaScript on your local machine. No data is ever sent to our servers.
            </p>
            <p>
                <strong>Instant Preview:</strong> See your XML code generate in real-time as you type. This immediate feedback loop ensures accuracy before deployment.
            </p>

            <h3 id="chapter3" className="text-xl font-bold text-gold mt-8">3. Advanced Configuration Guide</h3>
            <p>
                While the default settings work for most, power users can leverage advanced configurations to optimize crawl budgets.
            </p>
            <h4 className="font-bold text-white mt-4">Priority Settings (0.0 - 1.0)</h4>
            <p>
                Use <code>1.0</code> for your Homepage and major landing pages. Use <code>0.8</code> for category pages or main articles. 
                Use <code>0.5</code> for standard blog posts. Reserve lower priorities like <code>0.2</code> for legal disclaimers or archive pages.
            </p>
            <h4 className="font-bold text-white mt-4">Change Frequency</h4>
            <p>
                Be honest. Setting every page to <code>daily</code> when you only update monthly can damage your trust score with Google. 
                Use <code>hourly</code> only for breaking news sections or stock tickers.
            </p>

            <h3 id="chapter4" className="text-xl font-bold text-gold mt-8">4. SEO Best Practices for 2024 and Beyond</h3>
            <p>
                The landscape of SEO is shifting towards user experience and semantic understanding. However, technical foundations remain the bedrock.
            </p>
            <ol className="list-decimal pl-5 space-y-2">
                <li><strong>Clean URLs:</strong> Ensure your sitemap only contains canonical URLs (status 200). Do not include redirects (301) or missing pages (404).</li>
                <li><strong>Size Limits:</strong> A single sitemap file is limited to 50,000 URLs or 50MB. For larger sites, use a Sitemap Index file.</li>
                <li><strong>Robots.txt Integration:</strong> Always reference your sitemap location in your <code>robots.txt</code> file.</li>
            </ol>

            <h3 id="faq" className="text-xl font-bold text-gold mt-8">5. Frequently Asked Questions (FAQ)</h3>
            
            <div className="space-y-4 mt-4">
                <div className="bg-white/5 p-4 rounded border border-white/10">
                    <h4 className="font-bold text-gold">Is this sitemap generator free?</h4>
                    <p>Yes, Sitemap Generator Pro is 100% free and open source. It is maintained by HSINI MOHAMED as a contribution to the web developer community.</p>
                </div>
                <div className="bg-white/5 p-4 rounded border border-white/10">
                    <h4 className="font-bold text-gold">Does Google guarantee indexing?</h4>
                    <p>No. A sitemap is a suggestion, not a command. However, it significantly improves the chances of your pages being discovered and indexed faster.</p>
                </div>
                <div className="bg-white/5 p-4 rounded border border-white/10">
                    <h4 className="font-bold text-gold">How do I submit the file?</h4>
                    <p>Download the XML file, upload it to your website's root directory (e.g., public_html), and then submit the URL to Google Search Console.</p>
                </div>
            </div>

            <div className="mt-8 p-6 bg-gold/20 rounded-xl text-center border border-gold/40">
                <p className="text-lg font-bold text-white">Ready to optimize your website?</p>
                <p className="text-gray-300 mb-4">Scroll up and generate your sitemap in seconds.</p>
            </div>
          </div>
        </article>

        {/* Gradient Overlay */}
        {!isExpanded && (
          <div className="absolute bottom-0 left-0 w-full h-full bg-gradient-to-b from-transparent to-gray-900 pointer-events-none"></div>
        )}
      </div>

      <button 
        onClick={() => setIsExpanded(!isExpanded)} 
        className="w-full mt-2 bg-gray-800 hover:bg-gray-700 text-gold font-bold py-2 px-4 rounded transition-colors flex items-center justify-center gap-2 text-sm uppercase tracking-wide z-10 relative"
      >
        {isExpanded ? 'Read Less' : 'Read More'}
        <svg xmlns="http://www.w3.org/2000/svg" className={`h-4 w-4 transform transition-transform duration-300 ${isExpanded ? 'rotate-180' : ''}`} viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
        </svg>
      </button>
    </div>
  );
};